feat: enhance UI features and styling
Golf-Drill-Challenge-App/Golf-App pull request #139
Opened 2024-04-10 03:22 UTC by artkolpakov

This pull request implements several enhancements and adjustments to the user interface:

1. **Adjust Bar Chart Y-axis Styling**: improved the visual presentation of the bar chart by adjusting the Y-axis styling for better readability, aligning metrics with the chart's lines. [Ticket Nº107](https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/107)

| example 1 | example 2 | example 3 |
|---------|---------|---------|
| <img width="280" alt="Screenshot 2024-04-09 at 8 02 28 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/1ef24a61-1dc2-4dce-abda-582828bafced"> | <img width="279" alt="Screenshot 2024-04-09 at 8 02 53 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/d36cce0b-d24c-48bc-adfc-e3cede1c4f68"> | <img width="280" alt="Screenshot 2024-04-09 at 8 03 16 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/28ec3e0f-1272-4e55-9bea-08b87841da99">|

2. **Remove Email Update from User Profile Settings Modal:** removed the option for an email update from the user profile settings modal, as suggested by the coach. [Tiket Nº132](https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/132).

<img width="289" alt="Screenshot 2024-04-09 at 8 06 22 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/269e64f2-d0f4-4396-b094-89a63380361e">

3. **Display User's Email on Profile Card:** added functionality to display the user's email on the profile card. [Tiket Nº115](https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/115)

<img width="272" alt="Screenshot 2024-04-09 at 8 09 13 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/b3f057d4-05fb-47b2-8420-7df86da62bb4"> 

4. **Adjust Snapping Positions for Profile Settings Modal:** refactored the handling of snap points in the BottomSheetModal component to prevent full and half expansions. Additionally, ensured stability, as the snap points are now dynamically adjusted based on the visibility of the name/password input keyboard events (which wasn't working before). [Tiket Nº121](https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/121)

| name update snap points | name + password update snap points | keyboard input |
|---------|---------|---------|
| ![IMG_6699](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/ede44438-54ba-4a9e-a22a-23608bffdf7d) | ![IMG_6700](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/640b45cf-96ff-40bf-886e-be0b8fb7ef90) | ![IMG_6697](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/f27be824-b3e0-4840-a3cf-bfd8bb3f7039) |

These changes collectively improve the usability and visual appeal of the application, enhancing the overall user experience.

2024-04-10 03:53 UTC, FrankreedX requested changes
overall pretty good!

2024-04-10 03:53 UTC, FrankreedX commented on package-lock.json
no lmao

2024-04-10 03:53 UTC, FrankreedX commented on components/barChart.js
> +      top: -9.2,
These changes clashes with my changes so prob remove them

2024-04-10 04:43 UTC, FrankreedX approved these changes

2024-04-10 06:35 UTC, artkolpakov commented on package-lock.json
Yeah, your yMin, and yMax calculations are much cleaner 😂, thanks!!

2024-04-10 20:54 UTC, solderq35 requested changes
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/e93ff003-2078-4ebb-8625-a9605d27e3b6)

The signout button is still a little low imo (android, pixel 7 emulator)

![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/77fb5b46-9613-4ac0-89ce-1733d344397f)
- confirm password is unreachable on android and can't scroll lower (see other comment about react native keyboard aware scrollview library
  - Edit: that library seemed incompatible with bottomsheet

2024-04-10 20:54 UTC, solderq35 commented on app/content/profile/index.js
> +    const keyboardDidShowListener = Keyboard.addListener(
I'll have to look at this more closely later but I think you can simplify a lot of this by using this library (we use it for keyboard inputs elsewhere, e.g. signin)

https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view

2024-04-10 20:55 UTC, solderq35 commented on package-lock.json
Yes, please install yarn and regenerate yarn.lock (if you added or removed libraries)

2024-04-11 05:44 UTC, solderq35 reviewed
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/f10545a6-8f4b-4989-8276-92e86d8cbe52)

remember to rebase

2024-04-11 06:35 UTC, solderq35 commented
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/7f3b9501-6469-426a-8559-542d5533ea78)

Might work for android "confirm password" issues, otherwise use https://reactnative.dev/docs/platform to add platform specific styling (keyboardawareview library doesn't seem compatible with bottomsheet)

2024-04-11 07:31 UTC, solderq35 commented
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/5117ed3a-533d-4f0c-98d8-6efee1169e9e)

Increased vertical padding on Android so signout button is easier to see

2024-04-11 07:32 UTC, solderq35 approved these changes

2024-04-12 19:20 UTC, merged