Frankreed/style barchart buttons
Golf-Drill-Challenge-App/Golf-App pull request #187
Opened 2024-04-25 17:48 UTC by FrankreedX

2024-04-29 17:44 UTC, hannacol approved these changes

2024-05-03 03:51 UTC, solderq35 requested changes
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/f8ab819f-201c-45ad-8822-b06a75e2ef65)

Got this warning / error when clicking moving avg menu (android)

2024-05-03 03:57 UTC, FrankreedX commented
yeup that's the dropdown implementation

2024-05-03 22:32 UTC, solderq35 commented
> Got this warning / error when clicking moving avg menu (android)
> 
> ```
> VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
> ```

https://stackoverflow.com/a/70799037
This worked, `LogBox.ignoreLogs(['VirtualizedLists']);`

idk if worth commiting but for future reference about suppressing weird warnings we don't intend to fix

2024-05-03 23:09 UTC, merged