Coach view
Golf-Drill-Challenge-App/Golf-App pull request #208
Opened 2024-05-07 21:33 UTC by ajpert

adding assigning to the coach view. Eventually need to change tab layout

2024-05-07 22:00 UTC, FrankreedX requested changes
everything seems to work. Good job!

2024-05-17 19:14 UTC, FrankreedX commented on app/segments/drill/[id]/assignment/index.js
> +      for (const userId of selectedUsers) {
for loop works better for async here

2024-05-17 19:22 UTC, FrankreedX approved these changes
ehhhhhhhhhh

2024-05-17 19:32 UTC, hannacol approved these changes

2024-05-17 19:33 UTC, merged