Frankreed/fix numshot and gesturehandler bug
Golf-Drill-Challenge-App/Golf-App pull request #218
Opened 2024-05-15 01:17 UTC by FrankreedX

Fix a bunch of small bugs. This branch has been rebased on top of the barchart pr so it can't be merged right now...

2024-05-15 01:46 UTC, solderq35 commented
I got the shotnum bug fixed on my branch (https://github.com/Golf-Drill-Challenge-App/Golf-App/tree/solderq35/shotnum-hotfix), although if your branch also works we can just merge this one

2024-05-15 01:49 UTC, solderq35 requested changes

2024-05-15 01:49 UTC, solderq35 commented on app/content/assignments/index.js
> +  // Handle both errors of 'cannot read property "reduce" of undefined' and
This code is already existing in this file at line ~36. Is there a reason for this change?

Also I think there is a "login fixes" commit in this PR that is already in layout branch?

2024-05-15 02:00 UTC, solderq35 commented
Other than the question about the code in assignments/index.js, the code is working as expected on ios and android

2024-05-15 18:57 UTC, FrankreedX commented
cleaned up the history

2024-05-16 07:30 UTC, solderq35 approved these changes

2024-05-16 07:30 UTC, solderq35 commented
Look good to me

2024-05-16 23:08 UTC, merged