Frankreed/Allow coach to view all assignments (with unify all alerts merged)
Golf-Drill-Challenge-App/Golf-App pull request #232
Opened 2024-05-20 00:52 UTC by FrankreedX

EDIT: See https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/239

- Keeping this PR open just for reference, but probably not merging it unless the "merge all" PR above has issues?

2024-05-25 02:41 UTC, Gehrkej commented
Not sure why this is looking to merge into the all time record branch and not layout

2024-05-25 02:53 UTC, FrankreedX commented
because it's rebased off of all time record

2024-05-25 02:53 UTC, FrankreedX commented
if all time record merges first then this branch's target will change

2024-05-26 17:14 UTC, hannacol requested changes
Looks good overall. Couple things I would change styling on for better understanding for a user

2024-05-26 17:14 UTC, hannacol commented on components/assignmentList.js
> +    const pfpArr = playerList.slice(0, numPfp).map((player, index) => {
Are we able to make it display 3 image cards and then the last card displays "+{numAssignedPlayers - 3}" if there are more than 3 players assigned?

2024-05-26 23:44 UTC, solderq35 reviewed
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/6624ac1c-6daf-4278-aaa8-e16d23bb1327)

Just glancing at some of these commits, are some of these duplicated from layout branch (since all time records was already merged into layout)?

If we're short on time though, I guess just confirm everything works and forget about git history clutter.

2024-05-30 06:08 UTC, closed without merging