New Putting Drills
Golf-Drill-Challenge-App/Golf-App pull request #234
Opened 2024-05-21 22:16 UTC by hannacol

Added the following putting drills:

- Random Putting (#229)
- Inputted Putting Round (#225)

Inputted putting drill is a little janky with displaying the target value since it is done with an input rather than an already defined value.

2024-05-22 00:32 UTC, FrankreedX requested changes

2024-05-22 00:32 UTC, FrankreedX commented on app/segments/drill/[id]/submission/input.js
> +              shot.target = inputValues[j].distance;
Instead of making an exception for inputtedPutt everywhere, is it possible to make it more generic?

2024-05-22 00:32 UTC, FrankreedX commented on app/segments/drill/[id]/submission/input.js
> +                case "inputtedPutt":
Can you move all of this inputtedPutt specific code outside of the loop and handle all of them there so the code in the loop stays the same? Namely attemptShot[j].baseline and attemptShot[j].item.target can be at the start of the j loop

2024-05-22 00:32 UTC, FrankreedX commented on components/shotAccordion.js
> +              {props.drillInfo.requirements[0].type === "inputtedPutt" && (
use distanceMeasure here? like just add distanceMeasure to target on the database. It seems wrong tho...

2024-05-22 00:32 UTC, FrankreedX commented on components/shotAccordion.js
> +      switch (drillInfo.requirements[0].type) {
Let's not use target here. create a new field callled "distance" so you don't have to handle these inputtedPutt edge cases everywhere

2024-05-22 00:40 UTC, FrankreedX requested changes

2024-05-22 00:40 UTC, FrankreedX commented on app/segments/drill/[id]/submission/input.js
> +    case "inputtedPutt":
possibly use "fillClubTargets"

2024-05-22 00:40 UTC, FrankreedX commented on app/segments/drill/[id]/submission/input.js
> +    case "inputtedPutt":
rename it to "fillSequentialTargets" while you're at it

2024-05-23 16:47 UTC, FrankreedX approved these changes
looks good

2024-05-25 03:00 UTC, Gehrkej reviewed
Overall looks good to me, one other this is do we want to add the ruler icon to the drill index screen?
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/cc3f081f-b77b-41d7-b529-12f447cfcb41)

2024-05-25 04:51 UTC, Gehrkej approved these changes

2024-05-25 19:33 UTC, merged