Merged the 2 active PRs
Golf-Drill-Challenge-App/Golf-App pull request #239
Opened 2024-05-27 03:34 UTC by FrankreedX

2024-05-27 04:19 UTC, solderq35 requested changes
## Testing
Issues with team tab > player profile:
- Promotion and Demotion cache invalidation is not working (coach pov). Need to do pulldown refresh on team tab index page
  - Should promote or demote player navigate the coach back to the team index page, similar to remove or ban player actions?
- I think pulldown refresh isn't working anymore for team tab > player profile (both coach and player pov)
- Ban user cache invalidation not working (from coach POV. Need to refresh team tab index page)
  - ![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/c4b43e95-152c-4817-b17c-9b577a054128)
  - Note: Remove user does invalidate cache for team index page, from coach pov
- I sometimes got the error below but I couldn't reliably reproduce it, not sure why (for player removal or ban)
  - I think fixing the cache invalidation issues might fix this one? Needs more testing
  - ![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/d1f2995d-3f3f-4e39-b791-80384b1c7e92)

2024-05-27 21:14 UTC, solderq35 reviewed
I think it mostly looks good now (promote / demote / ban working now with cache invalidation), but there are a few "alert" left in chooseTeam.js and input.js, I can try to resolve them real quick

2024-05-27 23:01 UTC, solderq35 commented
## Changes (https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/239/commits/5073b08a8f305a0a737da6fdf423dd3f708cfc0f)
- Minor syntax changes:
  - Migrated remaining `alert` to `showDialog` syntax
  - Changed `console.errror` to `console.log(e)` + `showDialog`
- Make sure errors are handled for newly added functionality in remove user, blacklist (ban) user, promote / demote user, reset leaderboard (season)
- Remove outdated part of README about login
- Updated some of the "Document Updated" logs to be more specific

## Screenshots
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/687faf36-ee83-483f-8e83-9a5037c85995)
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/0d869bc7-c4be-4978-bc05-f41741aef182)
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/623e7dce-390d-40da-b93e-f097b7dd80ce)
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/68a8d502-90c5-4504-ba27-fdac50130e60)

2024-05-28 16:15 UTC, hannacol requested changes
Got an error about "Rendered fewer hooks than expected" when removing a player once, but did not happened again on a new user. All other promote, demote, and ban features work as intended

2024-05-28 16:16 UTC, hannacol commented
![Screenshot_20240528_090330_Expo Go.jpg](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91215417/60516102-f9d7-43d5-bee9-7673d96c146d)

2024-05-28 21:22 UTC, solderq35 commented
> Got an error about "Rendered fewer hooks than expected" when removing a player once, but did not happened again on a new user. All other promote, demote, and ban features work as intended

Maybe will try this library later to help debug it: https://www.npmjs.com/package/eslint-plugin-react-hooks

2024-05-28 22:03 UTC, solderq35 commented
Added [eslint react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) for now as debug (see comments of `.eslintrc.js` file for more details).

**Commands:**
- `yarn lint` (runs `yarn eslint .`, which checks all files)
- `yarn eslint ./hooks` (for more control over which files get checked, in this case checking `hooks` directory)

2024-05-29 00:34 UTC, solderq35 requested changes

2024-05-29 00:34 UTC, solderq35 commented on app/content/profile/index.js
>                          userId,
Should we be doing try / catch here? Maybe make a handler function? Also goes for similar calls to handleImageUpload in team index page (team image upload).

The hooks/imageUpload.js file (where the handleImageUpload function is defined) also needs checking to see if it has enough try catches.

2024-05-29 00:38 UTC, solderq35 commented
> Got an error about "Rendered fewer hooks than expected" when removing a player once, but did not happened again on a new user. All other promote, demote, and ban features work as intended

I think I fixed this now with https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/239/commits/823b1224612d035958041a9e067600584dabe885, but needs more testing.

I was able to reproduce the "fewer hooks" bug after trying to remove a user, but not after my changes. Basically, I just redefined invalidateMultipleKeys function as async, and did `await invalidateMultipleKeys` everywhere.

I suspect that the app was trying to do `navigation.goBack()` before all keys were invalidated, which caused the error.

Although `queryClient.invalidateQueries` is not inherently async (why I don't bother doing `await queryclient`), doing an async / await ensured the invalidation and navigation happened in the right order (so it's more of a Promise than await I guess).

2024-05-29 00:46 UTC, solderq35 requested changes

2024-05-29 00:46 UTC, solderq35 commented on app/content/team/index.js
> +      await invalidateMultipleKeys(queryClient, [["teamInfo"]]);
Do we need try / catch / showDialog here or in handleUpdate function?

2024-05-29 00:46 UTC, solderq35 commented on app/content/team/index.js
> +                        await invalidateMultipleKeys(queryClient, [
this might need try / catch / showdialog, see other comment about handleimageupload on this pr

2024-05-30 06:08 UTC, merged