Hannacol/Adding inputs and outputs to the Drill Description page
Golf-Drill-Challenge-App/Golf-App pull request #240
Opened 2024-05-27 17:46 UTC by hannacol

Drill Description screen was very bland, so we added the inputs and outputs of the drill to the description page

2024-05-27 23:10 UTC, solderq35 approved these changes
Looks Good To Me.

Some of the Drill Description text could maybe be a little bigger, but not a dealbreaker
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/3d8603cd-6e77-4a2a-a782-5ae7dd812b1a)

2024-05-28 18:04 UTC, FrankreedX commented
I still think as a user looking at this, this makes no sense... Inputs makes sense, but output is weird. Why is "Carry" outputted when that's my input? Output to where? etc.

2024-05-28 18:26 UTC, FrankreedX requested changes

2024-05-28 18:26 UTC, FrankreedX commented on components/drillDescription.js
> +  const sortedInputs = drillInfo.inputs.sort((a, b) => a.id > b.id);
Maybe sort this by prettyTitle so when prettyTitle starts with a different letter as the id, it's still sorted correctly. Maybe map it to prettytitle before sorting would be good too.

2024-05-28 21:21 UTC, FrankreedX commented
Maybe add requirements? So the player know what they're hitting against. Kinda like a tldr of the description

2024-06-03 00:23 UTC, FrankreedX commented
I'm still not a fan... but if we're rushing, this is good enough

2024-06-03 00:44 UTC, Gehrkej reviewed
Everything looks good other than the duplicate description on the modal we discussed.
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/6a287da9-6156-429b-9bd3-3ab59ad8a029)

2024-06-03 00:45 UTC, Gehrkej approved these changes
LGTM 👍

2024-06-03 00:53 UTC, solderq35 approved these changes

2024-06-03 00:53 UTC, merged