Hannacol/text based drills
Golf-Drill-Challenge-App/Golf-App pull request #247
Opened 2024-06-02 20:19 UTC by hannacol

Added logic for text based drills that do have inputs or outputted data.

- Removed buttons from drill index ppage as there are no leaderboards or stats associated with text drills
- Added screen for results page for text based drills to not display headers (may need reworked)
- Start drill takes you to a blank screen with submit drill (also may need reworked)

2024-06-03 00:42 UTC, solderq35 approved these changes

2024-06-03 01:02 UTC, FrankreedX requested changes
i dont like big if

2024-06-03 23:09 UTC, FrankreedX requested changes
Trying to go from Profile > IncreasedPressure shows this error
![Screenshot 2024-06-03 at 4 07 37 PM](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/2d0f670b-bd7f-429b-b2c5-93a842f7fbd8)

Maybe disable the View All Shots button in input.js
![Screenshot 2024-06-03 at 4 02 50 PM](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/e5154882-ccf9-42cc-8fb6-d53222ab3bc5)

Lastly, Make the "completed" checkbox more consistent with normal drill inputs
![Screenshot 2024-06-03 at 4 05 19 PM](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/d62318da-a483-4d95-9980-d51b99f9213f)

2024-06-04 06:06 UTC, FrankreedX commented
There are only 2 more things I want to request from this. It looks good otherwise.
First, hasStats = false drills shouldn't be visible in Team > Profile.
Second, in coach, completed assignment of drill with hasStats = false shouldn't be clickable.

2024-06-04 19:49 UTC, FrankreedX requested changes

2024-06-04 19:51 UTC, hannacol commented on app/segments/drill/[id]/submission/input.js
> +async function uploadTextDrill(userId, assignedTime, drillId, currentTeamId) {
Forgot to remove that. Thanks

2024-06-05 00:25 UTC, FrankreedX approved these changes
nice!

2024-06-05 00:27 UTC, merged