Fix test login (maybe)
Golf-Drill-Challenge-App/Golf-App pull request #90
Opened 2024-04-01 21:16 UTC by solderq35

## Issue

Original Error
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/baa2f716-5a2b-4c0f-b263-174b136d6e30)

In addition to the above error:
- Before, if you logged in as a regular user (running `yarn start`), didn't log out afterwards, then ran the app again as `yarn test`, then it tries to log you in as a regular user again instead of test user (due to persistent login code conflicting with the test user code)

## Changes
Tweaked auth logic to prevent persisting the regular user login if running in test mode (`yarn test`).

Deleting the contents of `node_modules` folder may also help with preventing the error, not sure.

Other changes to drill input is just what happened from running `yarn pretty`

2024-04-02 01:55 UTC, Gehrkej reviewed
Going through the troubleshooting options, I wasn't able to get `yarn test` to work even when deleting and reinstalling `node_modules` as well as appending a `-c `when running it. The solution I found that worked was just using `yarn start` and creating an account. Although with this, I found there was already an account made using my ONID. To reset my password, I navigated to firebase project, went to authentication, found my email and utilized the reset password email functionality. 

I believe Jeff's changes look good for preventing persistent login but was unable to fully test as I kept running into the initial issue.

2024-04-02 20:52 UTC, FrankreedX requested changes

2024-04-03 00:33 UTC, solderq35 commented on context/Auth.js
> +      if (!process.env.EXPO_PUBLIC_TEST_UID) {
I moved that if statement up, hopefully it's what you meant. Everything still seems to be working as expected

2024-04-03 00:35 UTC, solderq35 commented on context/Auth.js
> +      if (!process.env.EXPO_PUBLIC_TEST_UID) {
Altho the implementation will probably change with the login button version

2024-04-03 00:56 UTC, FrankreedX approved these changes
it's fine

2024-04-03 03:06 UTC, solderq35 commented
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/de69cf1c-9c9a-4f80-ac4b-66654653ab1b)

Test Login Button Version (no async storage on the test user)

2024-04-03 22:03 UTC, solderq35 commented
# Final Version? (yarn test without error)
This is the final version for latest commit of this PR.
## Testing
Run the following in terminal
- `git fetch`
  - Optional, just to make sure you get all the new branches from remote if applicable
- `git checkout solderq35/persist-async-storage`
- `git pull`
  - Optional, only if not up to date with remote
- `yarn`
- `yarn test -c`
  - No need to actually run the app on your phone yet, but let the app finish compiling, then quit with Ctrl / Cmd C
- `git checkout layout`
- git pull`
  - Optional, only if not up to date with remote
- `yarn test`
  - This time, **scan the QR code with your phone**, which should confirm if the error triggers or not (`...Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT... First argument of `require.context` should be a string denoting the directory to require.`)
  - The error should trigger here
- `git checkout solderq35/fix-test-login`
- git pull`
  - Optional, only if not up to date with remote
- `yarn test`
  - App should compile this time

Check my log file below in case I made a mistake in my instructions above
[reproduce-build-cache-bug.log](https://github.com/Golf-Drill-Challenge-App/Golf-App/files/14858795/reproduce-build-cache-bug.log)

## Explanation / Research (summary)
Git Branch differences
- `solderq35/persist-async-storage` changes some stuff in `app.json` to account for persistent caching
  - As explained by Expo dev Evan Bacon in [this thread](https://github.com/expo/expo/issues/23819#issuecomment-2019198302), changes to `app.json` may cause issues, which might resolved by clearing the bundler cache
    - However, this did not fully explain the bug at least in our use case, because Jake reported that sometimes clearing the cache `yarn test -c` did not fix the bug, and I also found that sometimes clearing the cache with `-c` was not enough
      - **NOTE: It seemed like another (relatively) fail-safe method was to add or remove some arbitrary package to package.json, then run `yarn`, then do `yarn test -c`**
        - This is why I intentionally only ran `yarn` on `solderq35/persist-async-storage` branch, and not on `layout`, nor `solderq35/fix-test-login` branch. Since `persist-async-storage` branch has package differences compared to `layout` and `fix-test-login` branches, running `yarn` on `persist-async-storage` along with `yarn test -c` "reset" the build cache onto the `persist-async-storage` branch, and caused the build cache to expect the app.json of `persist-async-storage` (theory)
        - It's also why I made sure that `babel-plugin-transform-inline-environment-variables` library was in both `persist-async-storage` and `fix-test-login` branches, so that the `fix-test-login` branch would at least compile without needing to run `yarn` to reinstall packages again
- The other half of the puzzle was the solution from this [other thread](https://github.com/expo/router/issues/41#issuecomment-1657674119) to make edits to `babel.config.js` to resolve issues with expo root / babel, and to add `babel-plugin-transform-inline-environment-variables` library
  - **For future reference, we seem to still be on Expo SDK 49 `"expo": "~49.0.15"` in package.json (which is why the first thread I linked from Evan Bacon is about SDK 49), so the babel / expo root / environmental variables stuff may need to be updated if we ever move to Expo SDK 50 or higher**
  - **Although it is generally still advised to clear the build cache with `-c`, it seemed the bug was more closely related to Babel and the "expo root" having some kind of conflict, after changes to app.json**

2024-04-03 22:54 UTC, FrankreedX approved these changes
sick. I have tested this on my machine and it works

2024-04-04 18:05 UTC, hannacol approved these changes

2024-04-04 19:49 UTC, merged