Attempt upload to firebase
Golf-Drill-Challenge-App/Golf-App pull request #91
Opened 2024-04-02 05:55 UTC by Gehrkej

### Issue
The current implementation was not uploading the results from an attempt to the database. This would mean after each attempt, all the attempt data was lost. 
**Related Issue:** #89 

### Changes
Created a function that will does the following:
- Takes in outputData
- Creates a new document in the "attempts" collection
- Appends the ID of the the new document with outputData which creates uploadData
- Updates the new document with uploadData

### Other Notes
- Currently there is a log message for the new document ID which can be used to validate an attempt has been uploaded through finding it on the firebase console

2024-04-02 21:05 UTC, FrankreedX requested changes

2024-04-02 21:05 UTC, FrankreedX commented on app/segments/drill/[id]/submission/input.js
> +    const uploadData = { ...outputData, id: newAttemptRef.id };
For some reason, this is creating a different formatting than the normal attempt. The data is wrapped in "outputData"
<img width="524" alt="Screenshot 2024-04-02 at 2 03 09 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/8bbee3a8-0083-42de-9a16-b3c3724e0b35">

2024-04-04 17:41 UTC, FrankreedX reviewed
I found the reason for the outputData thing. Check the "createOutputData" function in input.js. You're returning
  return {
    outputData,
  };
instead of
return outputData

2024-04-04 17:51 UTC, FrankreedX approved these changes
works

2024-04-04 20:23 UTC, artkolpakov approved these changes

2024-04-04 20:24 UTC, merged